<?php 
if (!$dbc) {
require_once("../mysql_connect.php");	
}
require_once('../common_functions.php');
require_once('admin_functions.php');
 ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us" dir="ltr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="robots" content="noindex, nofollow" />
<title>Poll Administration</title>
<style type="text/css" media="screen, print" title="Joe Dolson Poll Admin Styles">
@import "admin_styles.css";
</style>
</head>
<body>
<div id="outer">
<div id="head">
<h1><a href="http://www.joedolson.com/poll-with-php-and-mysql.php">Web Poll in PHP and MySQL</a></h1>
</div>
<div id="inner">

<?php 
list_polls();
?>

<?php if (isset($_POST) && $_POST['action'] == "create_poll") { ?>
	
<?php  
$caption = required_field($_POST['pollname']);
	$find = array(" ","'","\"","-","&",".",",");
	$replace = array("_","","","","_and_","","");
$pollname = strip_slashes(str_replace($find,$replace,strtolower($caption))); //(make lowercase, convert spaces)
$num_questions = required_field($_POST['num_questions']);
$num_options = required_field($_POST['num_options']);
$description = escape_data($_POST['description']);
$expires = escape_data($_POST['expires_y']) . '-' . escape_data($_POST['expires_m']) . '-' . escape_data($_POST['expires_d']) . ' 00:00:00';
$query = "INSERT INTO pollv2 VALUES ('','$pollname',$num_questions,NOW(),NOW(),'$expires','$description','$caption')";
//echo "$query";

if ($caption && $num_questions && $num_options && $expires) {

$update_query = mysql_query($query);

$create = "CREATE TABLE $pollname (
  qid int(11) NOT NULL auto_increment,
  question varchar(255) NOT NULL default '',
  num_options int(5) NOT NULL default '1',";
  for ($i=1;$i<=$num_options;$i++) {
	$create .= "c$i varchar(128) NOT NULL default '',";
  }
  for ($i=1;$i<=$num_options;$i++) {
	$create .= "r$i int(6) NOT NULL default '0',";
  }
$create .= "pollcolor varchar(32) NOT NULL default '009900',
  pollsize varchar(32) NOT NULL default '450x150',
  updated timestamp(14) NOT NULL,
  created datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (qid)
) TYPE=MyISAM AUTO_INCREMENT=1";

$create_table = mysql_query($create);
}
	if ($update_query && $create_table) {

?>
	<div class="response"><p>Successful creation of new poll.</p><p>Please define the questions and response options for your poll below.</p></div>


		<form method="post" action="<?php echo $php_self_submit; ?>">
		<div>
		<input type="hidden" name="action" value="describe_poll" />
		<input type="hidden" name="pollname" value="<?php echo strip_slashes($pollname); ?>" />
		<input type="hidden" name="num_questions" value="<?php echo $num_questions; ?>" />
		<input type="hidden" name="num_options" value="<?php echo $num_options; ?>" />
		</div>
		<fieldset>
		<legend>Describe the Questions Asked</legend>
		<p>
		All fields are required, although option fields which will not be used should be left empty.
		</p>
			<?php for ($i=1;$i <= $num_questions; $i++) { ?>
			<fieldset>
			<legend>Poll Information for Question <?php echo $i; ?></legend>
			<p>
			<label for="question<?php echo $i; ?>">Question</label> <input type="text" name="question<?php echo $i; ?>" id="question<?php echo $i; ?>" />
			</p>
			<fieldset>
			<legend>Options for Question <?php echo $i; ?></legend>
			<p>
			<label for="num_options<?php echo $i; ?>">Number of Options for This Question</label> <input type="text" name="num_options<?php echo $i; ?>" id="num_options<?php echo $i; ?>" size="3" value="<?php echo $num_options; ?>" /><br /><small>Leave the extra fields blank.</small>
			</p>
			<?php for ($r=1;$r<=$num_options;$r++) { ?>
			<p>
			<label for="option<?php echo $r; ?><?php echo $i; ?>">Option <?php echo $r; ?></label>
			<input type="text" name="option<?php echo $r; ?><?php echo $i; ?>" id="option<?php echo $r; ?><?php echo $i; ?>" />
			</p>
			<?php } ?>
			</fieldset>
			<p>
			<label for="pollcolor<?php echo $i; ?>">Graph Color Scheme</label> <input type="text" name="pollcolor<?php echo $i; ?>" id="pollcolor<?php echo $i; ?>" /><br /><small>6-digit Hexadecimal format. (Example: 990000)</small>
			</p>
			<p>
			<label for="pollsize<?php echo $i; ?>">Graph Size (Width x Height)</label> <input type="text" name="pollsize<?php echo $i; ?>" id="pollsize<?php echo $i; ?>" /><br /><small>Format as WWWxHHH (Example: 300x100). Charts are generated by the Google Chart API, which recommends that pie charts be at least twice as wide as they are tall, in order to make room for the text labels.</small>
			</p>
			</fieldset>
			<?php } ?>
		</fieldset>
		<p>
		<input type="submit" value="Submit" />
		</p>
		</form>

	<?php } else { ?>
		<div class="response"><p>Poll creation failed. Please try again.</p>
		<ol>
		<?php if (!$caption) {
		echo "<li>Poll title must be provided.</li>";
		}	
		if (!$num_questions) {
		echo "<li>Number of questions must be specified.</li>";
		} 
		if (!$num_options) {
		echo "<li>Maximum number of options available must be specified.</li>";
		}
		if (!$create_table) {
		echo "<li>There was an error creating the poll's database table.<p>$create</p></li>";
		}
		?>
		</ol>
<?php echo "<p><a href=\"index.php?pt=" . strip_slashes($caption) . "&amp;nq=$num_questions&amp;no=$num_options&amp;de=" . strip_slashes($description) . "\">Return to form</a></p>"; ?>
		</div>
	<?php } 
} else if (isset($_POST) && $_POST['action'] == "describe_poll") { 

	$num_questions = $_POST['num_questions'];
	$num_options = $_POST['num_options'];
	$pollname = $_POST['pollname'];
	echo "<ol>";
	for ($i=1; $i<=$num_questions; $i++) {
	$pollsize = $_POST['pollsize' .$i];
	$pollcolor = $_POST['pollcolor' . $i];
	$this_q_num_options = $_POST['num_options' . $i];
	$this_question = $_POST['question' . $i];
	$update = "INSERT INTO $pollname VALUES ('','$this_question',$this_q_num_options";
		for ($o=1;$o<=$num_options;$o++) {
		$question = $_POST['option' . $o . $i];
		$update .= ",'$question'";
		}
		for ($o=1;$o<=$num_options;$o++) {
		$update .= ",''";
		}		
	$update .= ",'$pollcolor','$pollsize',NOW(),NOW())";
	$update_qid = mysql_query($update);
	$errors = FALSE;
		if ($update_qid) {
		echo "<li>Options updated</li>";
		} else {
		$errors = TRUE;
		echo "<li>Options not updated</li>";
		}
	} 
	echo "</ol>";
	if ($errors == TRUE) {
	echo "<p>There were errors during the updating process. You will need to complete the update manually or visit the <a href=\"?edit=$pollname\">edit menu</a> for this poll.</p>";
	} else {
echo "<p>Your poll has been successfully created. You can add this poll to your website using the following code:</p>
<code><pre>
&lt;?php 
\$pollname = \"$pollname\"; // Current poll name
global \$formpath;
\$formpath = \"/poll\"; // --> Absolute path to poll installation location.
global \$ctype; 
\$ctype = \"p\"; // chart type (regular pie chart = 'p', 3d pie chart = 'p3'
include(\"poll.php\"); // --> Relative Path to poll.php include file
?&gt;	
</pre></code><p>You will need to update the fields marked with \"-->\" to reflect your actual installation paths.</p>";
	}
/// GET POLL TO EDIT	
} else if (isset($_GET['edit'])) { 

$pollname = escape_data($_GET['edit']);
	$get_general = mysql_query("SELECT * FROM pollv2 WHERE pollname = '$pollname'");
	$get_specific = mysql_query("SELECT * FROM $pollname");
	while($general = mysql_fetch_array($get_general,MYSQL_ASSOC)) {
		$num_questions = $general['num_questions'];
		$created = datetime($general['created'],'F j, Y');
		$expires = datetime($general['expires'],'F j, Y');
		$description = $general['description'];
		$caption = $general['caption'];
	
	echo "<h2>Editing &ldquo;$caption&rdquo;</h2><p>Poll has $num_questions"; $term = ($num_questions == 1) ? 'question' : 'questions'; echo " $term. Created $created, expires $expires.</p>
	<p><strong>Description:</strong><br />$description</p>";
	
	}
	echo "<form action=\"$php_self_submit\" method=\"post\">
	<div><input type=\"hidden\" value=\"edit_poll\" name=\"action\" />
	<input type=\"hidden\" value=\"$pollname\" name=\"pollname\" />
	<input type=\"hidden\" value=\"$num_questions\" name=\"num_questions\" /></div>";
	if ($get_specific) {
	while($specific = mysql_fetch_array($get_specific,MYSQL_ASSOC)) {
		$qid = $specific['qid'];
		$question = $specific['question'];
		$num_options = $specific['num_options'];
		$pollcolor = $specific['pollcolor'];
		$pollsize = $specific['pollsize'];
		$updated = datetime($specific['updated'],'F j, Y');
		
	echo "<fieldset>
	<legend>$question</legend>
	<p>
	<label for=\"question$qid\">Question</label> <input type=\"text\" value=\"$question\" name=\"question$qid\" id=\"question$qid\" />
	</p>
	<p>
	<label for=\"color$qid\">Color</label> <input type=\"text\" value=\"$pollcolor\" name=\"color$qid\" id=\"color$qid\" />
	</p>
	<p>
	<label for=\"graph$qid\">Graph dimensions</label> <input type=\"text\" value=\"$pollsize\" name=\"graph$qid\" id=\"graph$qid\" />
	</p>
	<p>
	<label for=\"num_options$qid\">Number of Options</label> <input type=\"text\" value=\"$num_options\" name=\"num_options$qid\" id=\"num_options$qid\" />
	</p>
	<fieldset>
	<legend>Options</legend>\n<ul>\n";
			for ($i=1;$i<=$num_options;$i++) {
				$option = $specific['c' . $i];
				echo "<li><label for=\"option$i$qid\">Option $i</label> <input type=\"text\" value=\"$option\" id=\"option$i$qid\" name=\"option$i$qid\" /></li>\n";
			}
	echo "\n</ul>\n</fieldset>\n</fieldset>";	
	}
	} else {
	echo "<div class='response'><p>There was an error in the creation of this poll's database. Sorry! You'll need to delete the record and try again.</p>
	<p><a href=\"?delete=$pollname\">Delete the record now.</a></p></div>";
	}
	echo "<p><input type=\"submit\" value=\"Submit\" /></p>";
	echo "</form>";


} else if(isset($_POST) && $_POST['action'] == "edit_poll") { 
$pollname = $_POST['pollname'];
$num_questions = $_POST['num_questions'];
for ($i=1;$i<=$num_questions;$i++) {
$update_query = "UPDATE $pollname SET ";
$question = $_POST['question' . $i];
$color = $_POST['color' . $i];
$graph = $_POST['graph' . $i];
$num_options = $_POST['num_options' . $i];

$update_query .= "question='$question',num_options=$num_options";

	for ($o=1;$o<=$num_options;$o++) {
	$option = $_POST['option' . $o . $i];
	$update_query .= ",c$o='$option'";
	}
$update_query .= ",pollcolor='$color',pollsize='$graph',updated=NOW() WHERE qid = $i";
//echo "<p>$update_query</p>";
$result = mysql_query($update_query);
}
if ($result) {
echo "<div class=\"response\">
<p>Updates successful.</p></div>";
} else {
echo "<div class=\"response\">
<p>Updates not successful.</p></div>";
}
} else if (isset($_GET['delete'])) {

$pollname = escape_data($_GET['delete']);

$delete = "DELETE FROM pollv2 WHERE pollname = '$pollname' LIMIT 1";
$mysql_delete = mysql_query($delete);
if ($mysql_delete) {
echo "<div class='response'><p>You have deleted $pollname</p><p><a href=\"index.php\">Return to add a new poll.</a></p></div>";
} else {
echo "<div class='response'><p>Failed to delete. This just isn't working out...</p></div>";
}

} else { ?>

<p>
Welcome to the administration of <a href="http://www.joedolson.com/poll-with-php-and-mysql.php">Joe Dolson's MySQL/PHP driven Poll</a>. This simple polling package allows you to run multiple simultaneous polls, each having unique characteristics including number of questions asked, number of options available for each question, color scheme of the chart generated, etc. Each poll is enclosed by a unique <code>div</code> with the format <code>poll_<samp>current_poll</samp></code> where &ldquo;current_poll&rdquo; is the name of the relevant poll. 
</p>
<p>
This is the administrative interface for your polls. You can create new polls and edit some parts of pre-existing polls. In later versions, the options available in this interface will probably grow. Keep track of new releases and updates <a href="http://feeds.feedburner.com/AccessibleDesign">by subscribing to my RSS feed</a>.
</p>

<form method="post" action="<?php echo $php_self_submit; ?>">
<div>
<input type="hidden" name="action" value="create_poll" />
</div>
<fieldset>
<legend>Create a New Poll</legend>
<p>
<label for="pollname">Poll Title</label> <input type="text" name="pollname" id="pollname" value="<?php if (isset($_GET['pt'])) { echo strip_slashes($_GET['pt']); } ?>" /> <strong><small>(required)</small></strong>
</p>
<p>
<label for="num_questions">Number of Questions</label> <input type="text" name="num_questions" id="num_questions" size="3" value="<?php if (isset($_GET['nq'])) { echo strip_slashes($_GET['nq']); } ?>" /> <strong><small>(required)</small></strong>
</p>
<p>
<label for="num_options">Max. Options Available</label> <input type="text" name="num_options" id="num_options" size="3" value="<?php if (isset($_GET['no'])) { echo strip_slashes($_GET['no']); } ?>" /> <strong><small>(required)</small></strong><br />
<small>Each question can have a different number of options; but this setting will determine the maximum number of options available.</small>
</p>
<fieldset>
<legend>Poll Expiration Date</legend><p>
<select name="expires_m" id="expires_m">
<option value="<?php echo date('m',strtotime('+1 month')); ?>"><?php echo date('F',strtotime('+1 month')); ?></option>
<option value="01">January</option>
<option value="02">February</option>
<option value="03">March</option>
<option value="04">April</option>
<option value="05">May</option>
<option value="06">June</option>
<option value="07">July</option>
<option value="08">August</option>
<option value="09">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option>
</select>
<select name="expires_d" id="expires_d">
<option value="<?php echo date('d',strtotime('+1 month')); ?>"><?php echo date('d',strtotime('+1 month')); ?></option>
<option value="01">1</option>
<option value="02">2</option>
<option value="03">3</option>
<option value="04">4</option>
<option value="05">5</option>
<option value="06">6</option>
<option value="07">7</option>
<option value="08">8</option>
<option value="09">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>
<select name="expires_y" id="expires_y">
<option value="<?php echo date('Y',strtotime('+1 month')); ?>"><?php echo date('Y',strtotime('+1 month')); ?></option>
<option value="2008">2008</option>
<option value="2009">2009</option>
<option value="2010">2010</option>
<option value="2011">2011</option>
<option value="2012">2012</option>
<option value="2013">2013</option>
</select> <strong><small>(required)</small></strong><br />
<small>Date after which votes will no longer be accepted. (Defaults to one month from today.)</small>
</p>
</fieldset>
<p>
<label for="description">Description of Poll</label> <input type="text" name="description" id="description" size="60" value="<?php if (isset($_GET['de'])) { echo strip_slashes($_GET['de']); } ?>" /> <strong><small>optional</small></strong><br />
<small>A textual description of the poll.</small>
</p>
</fieldset>
<p>
<input type="submit" value="Submit" />
</p>

</form>

<?php } ?>

<p><small><a href="http://www.joedolson.com/poll-with-php-and-mysql.php">Poll by Joe Dolson Accessible Web Design</a> | XHTML and PHP &copy; 2008 Joseph C Dolson, Javascript &copy; 2008 Christian Heilmann | <a href="http://creativecommons.org/licenses/by/3.0/">License Terms</a></small></p>
</div>
</div>
</body>
</html>